services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: q1008cam26_api_31415
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    environment:
      PORT: 17643

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: /backend
    container_name: q1008cam26_web_31415
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: /backend
    depends_on:
      api:
        condition: service_started
    ports:
      - "19631:18931"
